package com.delivery.orders.domain.model;

public enum SagaState {
    STARTED,
    RESTAURANT_VALIDATION_PENDING,
    RESTAURANT_VALIDATED,
    DELIVERY_ALLOCATION_PENDING,
    DELIVERY_ALLOCATED,
    PAYMENT_PROCESSING_PENDING,
    PAYMENT_PROCESSED,
    COMPLETED,
    RESTAURANT_COMPENSATION_PENDING,
    RESTAURANT_COMPENSATED,
    DELIVERY_COMPENSATION_PENDING,
    DELIVERY_COMPENSATED,
    PAYMENT_COMPENSATION_PENDING,
    PAYMENT_COMPENSATED,
    FAILED
}

