spring:
  application:
    name: restaurants-service
  
  profiles:
    active: local
  
  datasource:
    url: jdbc:postgresql://localhost:5432/restaurants_db
    username: restaurants_user
    password: restaurants_pass
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: restaurants-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  
  cache:
    type: redis
    redis:
      time-to-live: 30m

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    instances:
      default:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
  
  retry:
    instances:
      default:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2
  
  timelimiter:
    instances:
      default:
        timeout-duration: 5s

# Logging
logging:
  level:
    com.delivery.restaurants: DEBUG
    org.springframework.kafka: INFO
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Custom application properties
app:
  cache:
    l1:
      max-size: 1000
      expire-after-write: 10m
    l2:
      default-ttl: 30m
      restaurant-ttl: 1h
      menu-ttl: 2h
  
  kafka:
    topics:
      restaurant-created: restaurant.created
      restaurant-activated: restaurant.activated
      restaurant-deactivated: restaurant.deactivated
      menu-updated: menu.updated
      restaurant-rating-updated: restaurant.rating.updated

---
# Docker profile
spring:
  config:
    activate:
      on-profile: docker
  
  datasource:
    url: jdbc:postgresql://postgres:5432/restaurants_db
  
  kafka:
    bootstrap-servers: kafka:29092
  
  data:
    redis:
      host: redis

server:
  address: 0.0.0.0

