global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Kafka JMX metrics
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9101']

  # Spring Boot Actuator endpoints
  - job_name: 'restaurants-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['restaurants-service:8081']

  - job_name: 'orders-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['orders-service:8082']

  - job_name: 'delivery-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['delivery-service:8083']

  - job_name: 'payments-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['payments-service:8084']

  - job_name: 'bff-mobile'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['bff-mobile:8085']

  # Redis metrics (if redis_exporter is added)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis-exporter:9121']

  # PostgreSQL metrics (if postgres_exporter is added)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres-exporter:9187']

